App\Entity\Group:
    attributes:
        id:
            groups: ['group:read']
        name:
            groups: ['group:read', 'group:write']
        association:
            groups: ['group:read', 'group:write']
        users:
            groups: ['group:read', 'group:write']
        usersCount:
            groups: ['group:read', 'group:write']
        totalAmountGroup:
            groups: ['group:read']