App\Entity\User:
    attributes:
        id:
            groups: ['user:read','group:read']
        username:
            groups: ['user:read', 'user:write','group:read']
        firstname:
            groups: ['user:read', 'user:write','group:read']
        lastname:
            groups: ['user:read', 'user:write']
        address:
            groups: ['user:read', 'user:write']
        phoneNumber:
            groups: ['user:read', 'user:write']
        totalAmountUser:
            groups: ['user:read', 'group:read']
        groupe:
            groups: ['user:read', 'user:write']
        entries:
            groups: ['user:read', 'user:write', 'group:read']