App\Entity\User:
    attributes:
        id:
            groups: ['user:read']
        username:
            groups: ['user:read', 'user:write']
        firstname:
            groups: ['user:read', 'user:write']
        lastname:
            groups: ['user:read', 'user:write']
        address:
            groups: ['user:read', 'user:write']
        phoneNumber:
            groups: ['user:read', 'user:write']