App\Entity\Vola:
    attributes:
        id:
            groups: ['vola:read']
        montant:
            groups: ['vola:read', 'vola:write']
        description:
            groups: ['vola:read', 'vola:write']
        type:
            groups: ['vola:read', 'vola:write']