resources:
    App\Entity\User:
        attributes:
            normalization_context:
                groups: ['user:read']
            denormalization_context:
                groups: ['user:write']
  
    App\Entity\Vola:
        attributes:
            normalization_context:
                groups: ['vola:read']
            denormalization_context:
                groups: ['vola:write']
    App\Entity\Group:
        attributes:
            normalization_context:
                groups: ['group:read']
            denormalization_context:
                groups: ['group:write']
    App\Entity\Entry:
        attributes:
            normalization_context:
                groups: ['entry:read']
            denormalization_context:
                groups: ['entry:write']
    App\Entity\TypeCollectionFond:
        attributes:
            normalization_context:
                groups: ['typecollectionfond:read']
            denormalization_context:
                groups: ['typecollectionfond:write']
    App\Entity\Association:
        attributes:
            normalization_context:
                groups: ['association:read']
            denormalization_context:
                groups: ['association:write']